- name: check if Composer is installed
  stat: path=/usr/local/bin/composer
  register: composer_bin
  become: yes

- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer
  when: not composer_bin.stat.exists
  become: yes

- name: install Composer
  shell: php /tmp/composer-installer --install-dir=/usr/local/bin --filename=composer
  when: not composer_bin.stat.exists
  become: yes

- name: remove composer installer
  file:
    path: /tmp/composer-installer
    state: absent
  become: yes

- name: make Composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
  become: yes

- name: composer self update
  shell: composer self-update
  register: composer_self_update
  changed_when: "composer_self_update.stdout != ''"
  become: yes
